prefix: "§8[§bArmorTrimEdit§8] "

messages:
  no-permission: "§4No permission!"
  not-holding-armor: "§cThe item in your hand is not an armor item!"
  missing-items: "§cYou don't have the required items in your inventory!"
  not-enough-arguments: "§cNot enough arguments!"
  invalid-pattern-or-material: "§cInvalid pattern or material!"
  no-armor-trim: "§cThe item doesn't have an armor armor trim!"

gui-enabled: true

command-enabled: true

survival-mode-enabled: false