prefix: "§8[§bArmorTrimEdit§8] "
messages:
  no-permission: "§4No permission!"
  not-holding-armor: "§cThe item in your hand is not an Armor item!"
  missing-items: "§cYou don't have the required items in your inventory!"
survival-mode:
  enabled: false